#!/bin/sh

module="sbull"
device="sbull"
mode="777"


# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1


# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}0

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# for simpicity, hardcode the major number
#mknod /dev/${device}0 b ${major} 0


